---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/12 14:02
---

require("Framework.DoraSDK.DefineClass")
require("Framework.DoraSDK.HttpClient")