---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/13 14:38
---
require("Framework.Entity.EntityBase")
require("Framework.Entity.RemoteProxy")
