---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/12 14:02
---

--require(LuaCommonPrefix.."Managers.NetManager") --todo slua适配注释
--require(LuaCommonPrefix.."Managers.EventCenter")
Game.TableDataManager = Game.TableDataManager or  require(LuaCommonPrefix.."Managers.TableDataManager").new()